topnav_title: Deckhouse
site_title: Deckhouse
company_name:
  en: Flant
  ru: Флант
company_url:
  en: https://flant.com
  ru: https://flant.ru
url: https://deckhouse.io
urls:
  ru: https://deckhouse.ru
  en: https://deckhouse.io
canonical_url_prefix: /documentation/v1
site_description:
  en: "Deckhouse. An operator which creates homogeneous Kubernetes clusters anywhere and fully manages them. Manages all necessary addons to provide observability, security and service mesh."
  ru: "Deckhouse. Позволяет создавать идентичные Kubernetes-кластеры в любой инфраструктуре и полностью, «автомагически» управляет ими."
github_repo_path: /deckhouse/deckhouse
d8Revision: FE

metrics:
  google: G-4X28CEP7W2
  yandex: 78422802

chat_script_url:
  en: "https://crm.flant.ru/upload/crm/site_button/loader_2_qurrbf.js"
  ru: "https://crm.flant.ru/upload/crm/site_button/loader_3_20bbbd.js"

assets:
  precompile: ['**/*.*']

social_links:
  ru:
    telegram: https://t.me/deckhouse_ru
  en:
    telegram: https://t.me/deckhouse

output: web

exclude:
- .idea/
- .gitignore
- vendor
- Gemfile.lock
- Gemfile
- backend
- '*.sh'
- '*.yml'
- '*.yaml'
- docker-compose.yml
- modules_make_data
- modules_menu_skip

highlighter: rouge
feedback_disable: true

plugins:
  - jekyll-assets
  - jekyll-regex-replace
  - jekyll_include_plugin

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 parse_block_html: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      toc: false
      layout: "page"
      comments: false
      searchable: true
      sitemap_include: true
      topnav: topnav
      output: web
      sidebar: main
      multilang: true
      comparable: true
      lang: en
  - scope:
      path: "pages/includes"
      type: "pages"
    values:
      mode: "ssi"
      searchable: false
      sitemap_include: false
      layout: none
  - scope:
      path: "pages/guides"
      type: "pages"
    values:
      toc_in_sidebar: true
      toc: false
  - scope:
      path: "modules_ru"
      type: "pages"
    values:
      lang: ru
timezone: Europe/Moscow
