---
apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Cloud
cloud:
  provider: OpenStack
  prefix: 'candi-${PREFIX}'
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: '${KUBERNETES_VERSION}'
defaultCRI: '${CRI}'
clusterDomain: "cluster.local"
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  devBranch: '${DEV_BRANCH}'
  imagesRepo: dev-registry.deckhouse.io/sys/deckhouse-oss
  registryDockerCfg: '${DECKHOUSE_DOCKERCFG}'
---
apiVersion: deckhouse.io/v1
kind: OpenStackClusterConfiguration
layout: Standard
sshPublicKey: cert-authority,principals="tfadm" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIg88Qs3x5KR6IQnKYgif1hCig08hYh4eHrriCp4916KpjocdYgq7/TWTeeiJktEEkSo0E+8VJjW0IRk5qdBzPPGRWeSpktf18u4lrq5gWC1OkdDnIgioncxGihA1+ueclQj+eaJZRSh5E8//AROKBJSfAeN6sbn0SqCbZj3cqjR8bgDe4UgdPyXOpJ01iVWgzB0Bk8FHX3NRHdVwZDt7pBRX5Dwvd8z5kifxfWVOC0M5l9tH4dvdHNgthVYTTrIxC7fpAMNul4foe1+2iMg0GAe25MMmlgquWOK91yT2VSfvngsXpx8vb0juKS3Peq/B3TjAjmLxJBVxXx/rQA+AF7J1m6WgCB1bGNPl6Yc86v3SUdScACX+Qj147E5EzsCZbXRDiTq3GQQ9EnnmkK73obZrHkCeSSbH2rWln1IzzbgCc1R0yXpBT1Scjyx0ld31C5cSNq+sL21C0govCtSa93hgxggBUFdQ2a4c7U9knNB4khOF7nTtK543NDsJhXByjF6D484LTSV6Vrg5dbGFFxolaS++rgThtyUkH8BecuKFtxqwx+qxYlqAqO0E1QaUfEXbYtDQAFbcn6AcgU+M633uxzmvp9IYeAp6cy7T5Bbwu+jsErkviEkOwrASTMkJP4IXT6A3RLMNO0TvQwd9vP+kYL8Nk7a2QEHCCfwvpFw==
zones:
  - ru-3a
standard:
  internalNetworkDNSServers:
    - 8.8.8.8
  internalNetworkCIDR: 192.168.195.0/24
  internalNetworkSecurity: false
  externalNetworkName: "external-network"
provider:
  authURL: 'https://api.selvpc.ru/identity/v3'
  domainName: '48348'
  tenantID: 'ceda80a1b33844adb1cbddd20ee93585'
  username: 'deckhouse-e2e'
  password: '${OS_PASSWORD}'
  region: 'ru-3'
masterNodeGroup:
  replicas: ${MASTERS_COUNT}
  instanceClass:
    rootDiskSize: 50
    flavorName: e2e
    imageName: "redos-STD-MINIMAL-8.0.0"
  volumeTypeMap:
    ru-3a: "fast.ru-3a"
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: deckhouse
spec:
  version: 1
  enabled: true
  settings:
    highAvailability: false
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: istio
spec:
  version: 2
  enabled: true
  settings:
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: flant-integration
spec:
  enabled: false
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: global
spec:
  enabled: true
  settings:
    modules:
      publicDomainTemplate: "%s.k8s.smoke.flant.com"
  version: 1
