x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    properties:
      enablePodAntiAffinity:
        type: boolean
        default: false
      replicas:
        type: integer
        default: 2
      specificNodeType:
        type: string
        enum: ["system", "kube-dns"]
      stsNamespaces:
        type: array
        items:
          type: string
      stsPodsHostsAppenderWebhook:
        type: object
        default: {}
        properties:
          crt:
            type: string
          key:
            type: string
          ca:
            type: string
      resourcesRequests:
        type: object
        default: {}
        properties:
          vpa:
            type: object
            default: {}
            properties:
              mode:
                type: string
              cpu:
                type: object
                default: {}
                properties:
                  max:
                    type: string
                    x-examples: ["200m"]
                  min:
                    type: string
              memory:
                type: object
                default: {}
                properties:
                  max:
                    type: string
                  min:
                    type: string
                    x-examples: ["100Mi"]