{{- $prefix := .Values.global.clusterConfiguration.cloud.prefix | required "global.clusterConfiguration.cloud.prefix is required" }}
{{- $providerClusterConfiguration := .dynamix | required "internal.providerClusterConfiguration is required" }}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: DynamixCluster
metadata:
  name: "dynamix"
  namespace: d8-cloud-instance-manager
  {{- include "helm_lib_module_labels" (list . (dict "app" "capd-controller-manager")) | nindent 2 }}
spec:
  {{- if $prefix }}
  resourceGroup: "{{ $prefix }}-rg"
  internalNetwork: "{{ $prefix }}-vins"
  {{- end }}
  {{- if $providerClusterConfiguration.externalNetwork }}
  externalNetwork: "{{ $providerClusterConfiguration.externalNetwork }}"
  {{- end }}

