---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pp
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus" "prometheus" "cpp")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 9090
    protocol: TCP
    targetPort: https
  selector:
    prometheus: cpp
    app.kubernetes.io/name: prometheus-pp
{{- if (include "helm_lib_ha_enabled" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-main-0
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 9090
    targetPort: https
  selector:
    prometheus: cpp
    app.kubernetes.io/name: prometheus-pp
    statefulset.kubernetes.io/pod-name: prometheus-pp-main-0
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pp-main-1
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 9090
    targetPort: https
  selector:
    prometheus: cpp
    app.kubernetes.io/name: prometheus-pp
    statefulset.kubernetes.io/pod-name: prometheus-pp-main-1
{{- end }}
