---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pp
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus-pp" "prometheus" "pp")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 9090
    protocol: TCP
    targetPort: https
  selector:
    prometheus: pp
    app.kubernetes.io/name: prometheus-pp
