apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "auth")) | nindent 2 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
      - name: deckhouse-registry
      # {{- include "helm_lib_priority_class" (tuple . "cluster-low") | nindent 6 }}
      {{- include "helm_lib_node_selector" (tuple . "master") | nindent 6 }}
      # {{- include "helm_lib_tolerations" (tuple . "any-node") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_nobody_with_writable_fs" . | nindent 6 }}
      containers:
        - name: auth
          {{- include "helm_lib_module_container_security_context_read_only_root_filesystem" . | nindent 10 }}
          image: {{ include "helm_lib_module_image" (list . "dockerAuth") }}
          args:
            - -logtostderr
            - /etc/docker_auth/config.yaml
          ports:
            - name: "server"
              containerPort: 5001
          volumeMounts:
            - name: config-files
              mountPath: /etc/docker_auth/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config-files
          configMap:
            name: auth-config-files
