apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "auth")) | nindent 2 }}
spec:
  selector:
    app: auth
  ports:
    - name: "server"
      protocol: TCP
      port: 5001
      targetPort: 5001
