---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" .Chart.Name)) | nindent 2 }}
data:
  {{- $default := tpl .Values.loki.internal.config . | fromYaml }}
  {{- $custom := tpl .Values.loki.configCustom . | fromYaml }}
  {{- $merged := merge $default $custom }}
  config.yaml: |-
    {{- toYaml $merged | nindent 4 }}
