---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-provider
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" .Chart.Name)) | nindent 2 }}
data:
  TRIVY_REMOTE_URL: "http://trivy-server.d8-operator-trivy:4954"
  TRIVY_JAVA_DB_IMAGE: {{ printf "%s/security/trivy-java-db:1" .Values.global.modulesImages.registry.base | quote }}
  {{- if .Values.admissionPolicyEngine.denyVulnerableImages.insecureDbRegistry }}
  TRIVY_INSECURE: {{ .Values.admissionPolicyEngine.denyVulnerableImages.insecureDbRegistry | quote }}
  {{- else }}
  {{- if .Values.global.modulesImages.registry.CA }}
  TRIVY_REGISTRY_CA: | {{ $.Values.global.modulesImages.registry.CA | nindent 4 }}
  {{- end }}
  TRIVY_INSECURE: false
  {{- end }}
