---
apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Cloud
cloud:
  provider: GCP
  prefix: 'a${PREFIX}'
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: '${KUBERNETES_VERSION}'
defaultCRI: '${CRI}'
clusterDomain: "cluster.local"
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  devBranch: '${DEV_BRANCH}'
  imagesRepo: dev-registry.deckhouse.io/sys/deckhouse-oss
  registryDockerCfg: '${DECKHOUSE_DOCKERCFG}'
---
apiVersion: deckhouse.io/v1
kind: GCPClusterConfiguration
layout: WithoutNAT
sshKey: cert-authority,principals="tfadm" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIg88Qs3x5KR6IQnKYgif1hCig08hYh4eHrriCp4916KpjocdYgq7/TWTeeiJktEEkSo0E+8VJjW0IRk5qdBzPPGRWeSpktf18u4lrq5gWC1OkdDnIgioncxGihA1+ueclQj+eaJZRSh5E8//AROKBJSfAeN6sbn0SqCbZj3cqjR8bgDe4UgdPyXOpJ01iVWgzB0Bk8FHX3NRHdVwZDt7pBRX5Dwvd8z5kifxfWVOC0M5l9tH4dvdHNgthVYTTrIxC7fpAMNul4foe1+2iMg0GAe25MMmlgquWOK91yT2VSfvngsXpx8vb0juKS3Peq/B3TjAjmLxJBVxXx/rQA+AF7J1m6WgCB1bGNPl6Yc86v3SUdScACX+Qj147E5EzsCZbXRDiTq3GQQ9EnnmkK73obZrHkCeSSbH2rWln1IzzbgCc1R0yXpBT1Scjyx0ld31C5cSNq+sL21C0govCtSa93hgxggBUFdQ2a4c7U9knNB4khOF7nTtK543NDsJhXByjF6D484LTSV6Vrg5dbGFFxolaS++rgThtyUkH8BecuKFtxqwx+qxYlqAqO0E1QaUfEXbYtDQAFbcn6AcgU+M633uxzmvp9IYeAp6cy7T5Bbwu+jsErkviEkOwrASTMkJP4IXT6A3RLMNO0TvQwd9vP+kYL8Nk7a2QEHCCfwvpFw==
subnetworkCIDR: 10.36.0.0/24
masterNodeGroup:
  replicas: ${MASTERS_COUNT}
  zones:
  - europe-west3-b
  instanceClass:
    machineType: n1-standard-4
    image: projects/ubuntu-os-cloud/global/images/ubuntu-2404-noble-amd64-v20240523a
    diskSizeGb: 50
provider:
  region: europe-west3
  serviceAccountJSON: '${SERVICE_ACCOUNT_JSON}'
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: deckhouse
spec:
  version: 1
  enabled: true
  settings:
    highAvailability: false
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: global
spec:
  enabled: true
  settings:
    modules:
      publicDomainTemplate: "%s.k8s.smoke.flant.com"
  version: 1
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: flant-integration
spec:
  enabled: false
# move ingres from resources yaml for testing dhctl configuration with 3-rd party resources
---
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: nginx
spec:
  ingressClass: nginx
  inlet: LoadBalancer
  enableIstioSidecar: true
  nodeSelector:
    node-role.kubernetes.io/master: ''
  tolerations:
    - effect: NoSchedule
      operator: Exists
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: istio
spec:
  version: 2
  enabled: true
  settings:
