---
apiVersion: v1
kind: Secret
metadata:
  name: csi-credentials
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-controller")) | nindent 2 }}
type: Opaque
data:
  kubeconfigBase64: {{ .Values.cloudProviderDvp.internal.providerClusterConfiguration.provider.kubeconfigBase64 | b64enc | quote }}
