{{- range $index, $storageClass := .Values.cloudProviderDvp.internal.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  {{- include "helm_lib_module_labels" (list $ (dict "app" "csi-driver")) | nindent 2 }}
  {{- include "helm_lib_module_storage_class_annotations" (list $ $index $storageClass.name) | nindent 2 }}
  name: {{ $storageClass.name | quote }}
provisioner: disk.csi.virtualization.deckhouse.io
parameters:
  typeID: {{ $storageClass.type | quote }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}
