type: object
properties:
  storageClass:
    description: |-
      Имя StorageClass, который будет использоваться по умолчанию в кластере.

      Если значение не указано, то будет использоваться StorageClass, согласно настройке [глобального параметра storageClass](../../deckhouse-configure-global.html#parameters-storageclass).

      Настройка глобального параметра `storageClass` учитывается только при включении модуля. Изменение глобального параметра `storageClass` при включенном модуле не приведет к перезаказу диска.

      **Внимание.** Если указать значение, отличное от текущего (используемого в существующей PVC), диск будет перезаказан, и все данные удалятся.

      Если указать `false`, будет принудительно использоваться `emptyDir`.

  insecureDbRegistry:
    description: |
      Разрешает Trivy скачивать базы данных уязвимостей используя недоверенные HTTPS-подключения (не прошедшие проверку TLS-сертификата) или подключения по HTTP.

  additionalVulnerabilityReportFields:
    description: |
      Список дополнительных полей из базы уязвимостей, добавляемых к отчетам об уязвимостях (VulnerabilityReport).

  severities:
    description: |
      Фильтрация отчетов уязвимостей по уровню их критичности.

  linkCVEtoBDU:
    description: |
      Включить конвертацию отчетов уязвимостей. Заменяет уязвимости из базы CVE на данные из базы BDU и выводит их в отчете.

  tolerations:
    description: |
      Опциональные tolerations для компонентов `operator-trivy` и заданий сканирования (Jobs).

      Структура, аналогичная `spec.tolerations` пода Kubernetes.

      Если значение не указано или указано `false`, будет использоваться [автоматика](https://deckhouse.ru/products/kubernetes-platform/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).
  nodeSelector:
    description: |
      Опциональный селектор для компонентов `operator-trivy` и заданий сканирования (Jobs).

      Структура, аналогичная `spec.nodeSelector` пода Kubernetes.

      Если значение не указано или указано `false`, будет использоваться [автоматика](https://deckhouse.ru/products/kubernetes-platform/documentation/v1/#выделение-узлов-под-определенный-вид-нагрузки).

  reportResourceLabels:
    description: |
      Список дополнительных меток маркировки отчетов (VulnerabilityReport) Trivy.

      Значения этих меток будут соответствовать значениям меток сканируемых ресурсов.

  insecureRegistries:
    description: |
      Список адресов хранилищ образов контейнеров (container registry), к которым разрешены недоверенные HTTPS-подключения (не прошедшие проверку TLS-сертификата) и подключения по HTTP.

  registriesCA:
    description: |
      Список корневых сертификатов (CA) приватных хранилищ образов контейнеров (container registry).  

      Если сертификатов более одного, то они указываются последовательно без дополнительных переносов строк.

      *Пример:*
      ```yaml
      registriesCA: |-
        -----BEGIN CERTIFICATE-----
        MIIDfDCCAmSgAwIBAgIUPSUV/R5CLPXseGlF7YVCr9gt4LAwDQYJKoZIhvcNAQEL
        BQAwWDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQHDARUb3du
        MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xEzARBgNVBAMMCm5leHVzLXRlc3QwHhcN
        MjQxMTIxMDc1MjE2WhcNMjUxMTIxMDc1MjE2WjBYMQswCQYDVQQGEwJVUzEOMAwG
        KoZIhvcNAQELBQADggEBAClOsateVJj11YvRCDrfYZvPpMWDdZHiPxV9yQgkq7uP
        63Bzp+6zB1IM16cbgitrkCQEBJhvluRbHn4a6utrnA3dWMHH2+qzYRySQi2FOdPN
        Yl8pxqA9hnXFFAXPfI8Rk3UQLjTYhWsV5Xeis442dUopJJPExN9PNvJ6mrQX29e8
        GAN3OmUiK928Mkgdf+qooUsiPexNnRStJ2SulK/dLdQc4r8aZ8HP4JWl6vCSeDI0
        M6inHZJ77Q+xWy997+07q0wswjZ7f9SWkGMTVvDq8dp7HRTMvBtregBpRQecDvuj
        35CMgeCZPoBbgknXszKw7O0aTWgr7+ehBI+Q8sAXMJY=
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIDfDCCAmSgAwIBAgIUU6lD+uD4N9aOL4soKXNwY6OUj60wDQYJKoZIhvcNAQEL
        BQAwWDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVN0YXRlMQ0wCwYDVQQHDARUb3du
        MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xEzARBgNVBAMMCm5leHVzLXRlc3QwHhcN
        MjQxMTIxMTEzNjI1WhcNMjUxMTIxMTEzNjI1WjBYMQswCQYDVQQGEwJVUzEOMAwG
        A1UECAwFU3RhdGUxDTALBgNVBAcMBFRvd24xFTATBgNVBAoMDE9yZ2FuaXphdGlv
        ntCzLpMZ7zuKn7SMxmebphUQVuHKIC0CAwEAAaM+MDwwGwYDVR0RBBQwEocECoAA
        /ogiONhTGS/AchSvv40dtbXJG44xT2HBY2kGm/0euWa83ZYLqKHIEyvV52npeXSq
        tktThvl8peBkd/LS3PF/TPTxsplM1yaNvT0B5RrUSQ6IlKoshxY+xFktDboF/RIY
        eG8dt39/n7BduItv2hNaNwgU9GEUIQ6VQV+pbQFsvGcu9+1NxnJbUi/vXKSJEOkk
        AIyO7AA1TFlJ/m5Pd8SQYhz5WfCSIwFfp/H2rY73cyNUlAgY0oCxrwxjxzFIpdCF
        67hTqj/DMwFWC8qPS3iiGr1TO9phnjPUBV6ch5qed4I=
        -----END CERTIFICATE-----
      ```