---
apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Cloud
cloud:
  provider: vSphere
  prefix: '${PREFIX}'
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: '${KUBERNETES_VERSION}'
defaultCRI: '${CRI}'
clusterDomain: "cluster.local"
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  imagesRepo: dev-registry.deckhouse.io/sys/deckhouse-oss
  registryDockerCfg: '${DECKHOUSE_DOCKERCFG}'
  devBranch: '${DEV_BRANCH}'
---
apiVersion: deckhouse.io/v1
kind: VsphereClusterConfiguration
sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDT7Y2xnnixeZHp3biNEUqFzvq/lu2y66SWuTQS6AQOGEIok0Ep56b0UtPoqA6EIXRS9JJOegDpK3UxiDGlxNPIaiq7QGM7qTH/rJ3NsgMT7MLOnK3VQ/PNM6iuPS2jwmd/VwcgjR44s+uLBS8vsJnP7NT5ymnR72b1vuIDAih5OQkkSg26z84fpLVbKsnImny1TdPlVfR5SyUXUZaDn/JlYC4eraG5pp0fqyUpo39KsBaQo2ngLLFOsyzKz1hjB+dGaBlRdJOXj4AP8d48h8Qg+6b1mCDqsctK3SGq05NREgSjZ0J3opoaB2DBd7ztHlhYatjoCHfsDxcByJnqT5w+EqyruiysxOY3j6EC0GqBQoGT744ugBK0Oy1KOBIMIMyJfrQ62QGsmmsYRg5PQK2bOjLGpSHc4Yys3TMVkMLBFS/9pNGI9EDDPZwkeOM0hN1g/vqzOz6Uiw+g347RkeCB/95G9+9oxh7MkPcies8I4uJVJGSgxKEes58U2+krb+2hKZiXblO81sAMwB3nIRs3NizuAGOtu0ppsvs2GbZhpIvT5om4onvniP866Pd7FLm37guMxh/cx9/n3qvaTkpgcDWZWtpk8Cfj2std6AEwE8GY+YQfCmcMOZXam6/qO5FUfQFT2WHTDPBTPGr7yjRdGsfwtZLwM0kRVN4ZBx/YEw== root@c4e850b2e8ac"
layout: Standard
vmFolderPath: 'flant-e2e-tests/${PREFIX}'
regionTagCategory: k8s-region
zoneTagCategory: k8s-zone
region: X2
zones:
- X2-A
externalNetworkNames:
- msk3-k8s-1203
internalNetworkNames:
- DEVOPS_36
internalNetworkCIDR: 172.16.25.0/24
baseResourcePool: kubernetes-stage/cloud-layout-tests
masterNodeGroup:
  replicas: ${MASTERS_COUNT}
  instanceClass:
    numCPUs: 4
    memory: 8192
    template: Templates/ubuntu-jammy-22.04-packer
    mainNetwork: msk3-k8s-1203
    additionalNetworks:
    - DEVOPS_36
    datastore: 3par_4_Lun105
    rootDiskSize: 50
    runtimeOptions:
      nestedHardwareVirtualization: false
provider:
  server: p-vc-3.${VSPHERE_BASE_DOMAIN}
  username: dvadm@vsphere.local
  password: '${VSPHERE_PASSWORD}'
  insecure: true
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: deckhouse
spec:
  version: 1
  enabled: true
  settings:
    highAvailability: false
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: flant-integration
spec:
  enabled: false
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: keepalived
spec:
  enabled: true
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: network-gateway
spec:
  enabled: true
  version: 1
  settings:
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - operator: Exists
    publicAddress: 10.220.203.240
    subnet: 172.16.25.0/24
    dns:
      servers:
        - 10.80.44.235
        - 10.220.8.235
      search:
        - ${VSPHERE_BASE_DOMAIN}
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: global
spec:
  enabled: true
  settings:
    modules:
      publicDomainTemplate: "%s.k8s.smoke.flant.com"
  version: 1
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: istio
spec:
  version: 2
  enabled: true
  settings:
