---
apiVersion: deckhouse.io/v1
kind: ClusterConfiguration
clusterType: Cloud
cloud:
  provider: vSphere
  prefix: '${PREFIX}'
podSubnetCIDR: 10.111.0.0/16
serviceSubnetCIDR: 10.222.0.0/16
kubernetesVersion: '${KUBERNETES_VERSION}'
defaultCRI: '${CRI}'
clusterDomain: "cluster.local"
---
apiVersion: deckhouse.io/v1
kind: InitConfiguration
deckhouse:
  imagesRepo: dev-registry.deckhouse.io/sys/deckhouse-oss
  registryDockerCfg: '${DECKHOUSE_DOCKERCFG}'
  devBranch: '${DEV_BRANCH}'
---
apiVersion: deckhouse.io/v1
kind: VsphereClusterConfiguration
sshPublicKey: cert-authority,principals="tfadm" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIg88Qs3x5KR6IQnKYgif1hCig08hYh4eHrriCp4916KpjocdYgq7/TWTeeiJktEEkSo0E+8VJjW0IRk5qdBzPPGRWeSpktf18u4lrq5gWC1OkdDnIgioncxGihA1+ueclQj+eaJZRSh5E8//AROKBJSfAeN6sbn0SqCbZj3cqjR8bgDe4UgdPyXOpJ01iVWgzB0Bk8FHX3NRHdVwZDt7pBRX5Dwvd8z5kifxfWVOC0M5l9tH4dvdHNgthVYTTrIxC7fpAMNul4foe1+2iMg0GAe25MMmlgquWOK91yT2VSfvngsXpx8vb0juKS3Peq/B3TjAjmLxJBVxXx/rQA+AF7J1m6WgCB1bGNPl6Yc86v3SUdScACX+Qj147E5EzsCZbXRDiTq3GQQ9EnnmkK73obZrHkCeSSbH2rWln1IzzbgCc1R0yXpBT1Scjyx0ld31C5cSNq+sL21C0govCtSa93hgxggBUFdQ2a4c7U9knNB4khOF7nTtK543NDsJhXByjF6D484LTSV6Vrg5dbGFFxolaS++rgThtyUkH8BecuKFtxqwx+qxYlqAqO0E1QaUfEXbYtDQAFbcn6AcgU+M633uxzmvp9IYeAp6cy7T5Bbwu+jsErkviEkOwrASTMkJP4IXT6A3RLMNO0TvQwd9vP+kYL8Nk7a2QEHCCfwvpFw==
layout: Standard
vmFolderPath: 'flant-e2e-tests/${PREFIX}'
regionTagCategory: k8s-region
zoneTagCategory: k8s-zone
region: X2
zones:
- X2-A
externalNetworkNames:
- msk3-k8s-1203
internalNetworkNames:
- DEVOPS_36
internalNetworkCIDR: 172.16.25.0/24
baseResourcePool: kubernetes-stage/cloud-layout-tests
masterNodeGroup:
  replicas: ${MASTERS_COUNT}
  instanceClass:
    numCPUs: 4
    memory: 8192
    template: Templates/ubuntu-jammy-22.04-packer
    mainNetwork: msk3-k8s-1203
    additionalNetworks:
    - DEVOPS_36
    datastore: 3par_4_Lun105
    rootDiskSize: 50
    runtimeOptions:
      nestedHardwareVirtualization: false
provider:
  server: p-vc-3.${VSPHERE_BASE_DOMAIN}
  username: dvadm@vsphere.local
  password: '${VSPHERE_PASSWORD}'
  insecure: true
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: deckhouse
spec:
  version: 1
  enabled: true
  settings:
    highAvailability: false
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: flant-integration
spec:
  enabled: false
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: keepalived
spec:
  enabled: true
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: network-gateway
spec:
  enabled: true
  version: 1
  settings:
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - operator: Exists
    publicAddress: 10.220.203.240
    subnet: 172.16.25.0/24
    dns:
      servers:
        - 10.80.44.235
        - 10.220.8.235
      search:
        - ${VSPHERE_BASE_DOMAIN}
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: global
spec:
  enabled: true
  settings:
    modules:
      publicDomainTemplate: "%s.k8s.smoke.flant.com"
  version: 1
---
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: istio
spec:
  version: 2
  enabled: true
  settings:
