---
apiVersion: deckhouse.io/v1alpha1
kind: KeepalivedInstance
metadata:
  name: master-gateway
spec:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
  - operator: Exists
  vrrpInstances:
  - id: 1
    interface:
      detectionStrategy: NetworkAddress
      networkAddress: "172.16.25.0/24"
    virtualIPAddresses:
    - address: "172.16.25.1/24"
    - address: "10.220.203.240/24"
      interface:
        detectionStrategy: DefaultRoute
---
apiVersion: deckhouse.io/v1
kind: VsphereInstanceClass
metadata:
  name: system
spec:
  numCPUs: 4
  memory: 8192
  rootDiskSize: 20
  mainNetwork: msk3-k8s-1203
  additionalNetworks:
    - DEVOPS_36
  datastore: 3par_4_Lun105
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: system
spec:
  nodeType: CloudEphemeral
  cloudInstances:
    zones:
    - X2-A
    minPerZone: 1
    maxPerZone: 1
    classReference:
      kind: VsphereInstanceClass
      name: system
  nodeTemplate:
    labels:
      node-role.deckhouse.io/system: ""
    taints:
    - effect: NoExecute
      key: dedicated.deckhouse.io
      value: system
  chaos:
    mode: Disabled
---
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: main
spec:
  ingressClass: nginx
  inlet: HostPort
  hostPort:
    httpPort: 80
    httpsPort: 443
  nodeSelector:
    node-role.kubernetes.io/master: ''
  tolerations:
    - effect: NoSchedule
      operator: Exists
---
apiVersion: deckhouse.io/v1
kind: NodeUser
metadata:
  name: user-e2e
spec:
  uid: 10056
  sshPublicKeys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDT7Y2xnnixeZHp3biNEUqFzvq/lu2y66SWuTQS6AQOGEIok0Ep56b0UtPoqA6EIXRS9JJOegDpK3UxiDGlxNPIaiq7QGM7qTH/rJ3NsgMT7MLOnK3VQ/PNM6iuPS2jwmd/VwcgjR44s+uLBS8vsJnP7NT5ymnR72b1vuIDAih5OQkkSg26z84fpLVbKsnImny1TdPlVfR5SyUXUZaDn/JlYC4eraG5pp0fqyUpo39KsBaQo2ngLLFOsyzKz1hjB+dGaBlRdJOXj4AP8d48h8Qg+6b1mCDqsctK3SGq05NREgSjZ0J3opoaB2DBd7ztHlhYatjoCHfsDxcByJnqT5w+EqyruiysxOY3j6EC0GqBQoGT744ugBK0Oy1KOBIMIMyJfrQ62QGsmmsYRg5PQK2bOjLGpSHc4Yys3TMVkMLBFS/9pNGI9EDDPZwkeOM0hN1g/vqzOz6Uiw+g347RkeCB/95G9+9oxh7MkPcies8I4uJVJGSgxKEes58U2+krb+2hKZiXblO81sAMwB3nIRs3NizuAGOtu0ppsvs2GbZhpIvT5om4onvniP866Pd7FLm37guMxh/cx9/n3qvaTkpgcDWZWtpk8Cfj2std6AEwE8GY+YQfCmcMOZXam6/qO5FUfQFT2WHTDPBTPGr7yjRdGsfwtZLwM0kRVN4ZBx/YEw== root@c4e850b2e8ac"
  passwordHash: "$6$vUn3pWjfLzk8iARF$JTR4j5IV0u5aD7O/xK8ZBN4ie/1TE1YwLzfPutpJ4BCJozy1Rgw.Pl4x6gDiUwsPyQcylCuf/oxbL0iMqFdPL/"
  isSudoer: true
---
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .secret-file: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dotfile-cm
  namespace: d8-system
data:
  .file: "content"
