- name: oom-kills
  rules:
  - record: oom_kills:normalized
    expr: |-
      sum by (namespace, pod, container) (
        kube_pod_container_info * on (uid) group_left
        sum by (uid) (label_replace(klog_oomkill{task_memcg=~".*burstable/pod.*"}, "uid", "$1", "task_memcg", ".+burstable/pod(.*)"))
      )
  - record: oom_kills:normalized
    expr: |-
      sum by (namespace, pod, container) (
        kube_pod_container_info * on (uid) group_left
        sum by (uid) (label_replace(klog_oomkill{task_memcg=~".*burstable/pod.*"}, "uid", "$1", "task_memcg", ".+burstable/pod(.*)/.+"))
      )
  - record: oom_kills:normalized
    expr: |-
      sum by (namespace, pod, container) (
        kube_pod_container_info * on (uid) group_left
        sum by (uid) (label_replace(klog_oomkill{task_memcg=~".*kubepods/pod.*"}, "uid", "$1", "task_memcg", ".+kubepods/pod(.*)"))
      )
  - record: oom_kills:normalized
    expr: |-
      sum by (namespace, pod, container) (
        kube_pod_container_info * on (uid) group_left
        sum by (uid) (label_replace(klog_oomkill{task_memcg=~".*kubepods/pod.*"}, "uid", "$1", "task_memcg", ".+kubepods/pod(.*)/.+"))
      )
