- name: oom-kills
  rules:
  - record: oom_kills:normalized
    expr: |-
      max by (namespace, pod) (
        label_replace(kube_pod_info, "raw_pod_id", "$1$2$3$4$5", "uid", "(.+)-(.+)-(.+)-(.+)-(.+)")
        * on (raw_pod_id) group_left
        max by (raw_pod_id) (
          label_replace(
            label_replace(klog_oomkill{task_memcg=~".*slice.*"}, "raw_pod_id", "$1", "task_memcg", ".+-pod(.+).slice"),
              "raw_pod_id", "$1$2$3$4$5", "raw_pod_id", "(.+)_(.+)_(.+)_(.+)_(.+)"
          )
        )
      )
  - record: oom_kills:normalized
    expr: |-
      max by (namespace, pod, container) (
        label_replace(kube_pod_container_info{container_id!=""}, "raw_container_id", "$1", "container_id", "containerd://(.+)")
        * on (raw_container_id) group_left
        max by (raw_container_id) (label_replace(klog_oomkill{task_memcg=~".+cri-containerd-.+.scope"}, "raw_container_id", "$1", "task_memcg", ".+cri-containerd-(.+).scope"))
      )
  - record: oom_kills:normalized
    expr: |-
      max by (namespace, pod, container) (
        kube_pod_container_info * on (uid) group_left
        max by (uid) (label_replace(klog_oomkill{task_memcg=~".*burstable/pod.*"}, "uid", "$1", "task_memcg", ".+burstable/pod(.*)"))
      )
  - record: oom_kills:normalized
    expr: |-
      max by (namespace, pod, container) (
        kube_pod_container_info * on (uid) group_left
        max by (uid) (label_replace(klog_oomkill{task_memcg=~".*burstable/pod.*"}, "uid", "$1", "task_memcg", ".+burstable/pod(.*)/.+"))
      )
  - record: oom_kills:normalized
    expr: |-
      max by (namespace, pod, container) (
        kube_pod_container_info * on (uid) group_left
        max by (uid) (label_replace(klog_oomkill{task_memcg=~".*kubepods/pod.*"}, "uid", "$1", "task_memcg", ".+kubepods/pod(.*)"))
      )
  - record: oom_kills:normalized
    expr: |-
      max by (namespace, pod, container) (
        kube_pod_container_info * on (uid) group_left
        max by (uid) (label_replace(klog_oomkill{task_memcg=~".*kubepods/pod.*"}, "uid", "$1", "task_memcg", ".+kubepods/pod(.*)/.+"))
      )
