x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    properties:
      effectiveStorageClass:
        default: false
        oneOf:
          - type: string
          - type: boolean
      etcd:
        type: object
        default: {}
        properties:
          addresses:
            type: array
            description: |
              Array of etcd addresses.
            x-examples:
              - ["10.0.0.1:2379", "10.0.0.2:2379", "10.0.0.3:2379"]
            default: []
            items:
              type: string
              pattern: '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[1-9][0-9]{0,4}$'
