type: object
properties:
  cluster:
    type: object
    default: {}
    description: |
      Seaweedfs cluster's settings
    properties:
      size:
        type: integer
        description: |
          The number of nodes
        x-examples:
          - 1
          - 3
  registryMode:
    type: string
    enum:
      - Direct
      - Proxy
      - Detached
    default: Direct
    description: |
      Registry mode
    x-example:
      - registryMode: Proxy
      - registryMode: Direct
      - registryMode: Detached
  upstreamRegistry:
    type: object
    x-example:
      - upstreamRegistry:
          upstreamRegistryHost: dev-registry.deckhouse.io
          upstreamRegistryScheme: https
          upstreamRegistryCa: ""
          upstreamRegistryPath: sys/deckhouse-oss
          upstreamRegistryUser: license-token
          upstreamRegistryPassword: "123456"
    properties:
      upstreamRegistryHost:
        type: string
        description: |
          Host of upstream registry
        x-example:
          - dev-registry.deckhouse.io
      upstreamRegistryScheme:
        type: string
        description: |
          Scheme of upstream registry
        x-example:
          - https
      upstreamRegistryCa:
        type: string
        description: |
          CA of upstream registry
        x-example:
          - ""
      upstreamRegistryPath:
        type: string
        description: |
          Path of upstream registry
        x-example:
          - sys/deckhouse-oss
      upstreamRegistryUser:
        type: string
        description: |
          User of upstream registry
        x-example:
          - license-token
      upstreamRegistryPassword:
        type: string
        description: |
          Password of upstream registry
        x-example:
          - "123456"
