x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    properties:
      effectiveStorageClass:
        default: false
        oneOf:
          - type: string
          - type: boolean
      registryCA:
        type: object
        default: { }
        x-examples:
          - cert: "-----BEGIN CERTIFICATE-----....-----END CERTIFICATE-----"
            key: "-----BEGIN RSA PRIVATE KEY-----....-----END RSA PRIVATE KEY----"
        properties:
          cert:
            type: string
          key:
            type: string
