---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-controller-manager
  namespace: d8-cloud-provider-dvp
  {{- include "helm_lib_module_labels" (list . (dict "app" "cloud-controller-manager")) | nindent 2 }}
type: Opaque
data:
  kubeconfigBase64: {{ .Values.cloudProviderDvp.internal.providerClusterConfiguration.provider.kubeconfigBase64 | b64enc | quote }}
