{{- define "system_registry_manager_resources" }}
cpu: 25m
memory: 40Mi
{{- end }}

{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: system-registry-manager
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "system-registry-manager" "workload-resource-policy.deckhouse.io" "master")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: DaemonSet
    name: system-registry-manager
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: system-registry-manager
      minAllowed:
        {{- include "system_registry_manager_resources" . | nindent 8 }}
      maxAllowed:
        cpu: 50m
        memory: 80Mi
{{- end }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: system-registry-manager
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "system-registry-manager")) | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: system-registry-manager
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0%
  template:
    metadata:
      labels:
        app: system-registry-manager
    spec:
      {{- include "helm_lib_node_selector" (tuple . "master") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_root" . | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "any-node" "uninitialized") | nindent 6 }}
      imagePullSecrets:
      - name: deckhouse-registry
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - name: system-registry-manager
        {{- include "helm_lib_module_container_security_context_read_only_root_filesystem_capabilities_drop_all_and_add" (list . (list "SYS_CHROOT")) | nindent 8 }}
        {{- if and (hasKey $.Values.systemRegistry "imagesOverride") (hasKey $.Values.systemRegistry.imagesOverride "registryManager") (ne $.Values.systemRegistry.imagesOverride.registryManager "") }}
        image: {{ $.Values.systemRegistry.imagesOverride.registryManager }}
        imagePullPolicy: Always
        {{- else }}
        image: {{ include "helm_lib_module_image" (list . "systemRegistryManager") }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: etc-kubernetes
        - mountPath: /tmp
          name: tmp
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: REGISTRY_ADDRESS
          value: {{ $.Values.global.modulesImages.registry.address }}
        - name: REGISTRY_PATH
          value: {{ $.Values.global.modulesImages.registry.path }}
        - name: IMAGE_DOCKER_AUTH
          value: "{{ $.Values.global.modulesImages.digests.systemRegistry.dockerAuth }}"
        - name: IMAGE_DOCKER_DISTRIBUTION
          value: "{{ $.Values.global.modulesImages.digests.systemRegistry.dockerDistribution }}"
        - name: IMAGE_SEAWEEDFS
          value: "{{ $.Values.global.modulesImages.digests.systemRegistry.seaweedfs }}"
        {{- include "helm_lib_envs_for_proxy" . | nindent 8 }}
        ports:
        - name: http-healthz
          protocol: TCP
          containerPort: 8097
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8097
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /readyz
            scheme: HTTP
            port: 8097
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 8
        resources:
          requests:
            {{- include "helm_lib_module_ephemeral_storage_logs_with_extra" 50 | nindent 12 }}
{{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler") }}
            {{- include "system_registry_manager_resources" . | nindent 12 }}
{{- end }}
      priorityClassName: system-cluster-critical
      volumes:
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes/
          type: DirectoryOrCreate
      - name: tmp
        emptyDir: {}
