##### For specific env
{{- if (eq $.Values.systemRegistry.environment "Vadim")  }}
#####

{{- $templateConfigFilesValues := (include "template-config-files-values" $ ) | fromYaml }}
---
apiVersion: v1
kind: Secret
metadata:
  name: d8-system-registry-manager-configs
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "d8-system-registry")) | nindent 2 }}
type: Opaque
data:
{{- range $templateConfigFilesValues.files }}
  {{- $ext := .filePath | base | ext }}
  {{- $templateName := .templateName  }}
  {{- $content := (include $templateName $ ) }}
  {{- if (eq $ext ".toml") }}
  "{{ $templateName }}": {{ $content | fromYaml | toToml | b64enc }}
  {{- else if (eq $ext ".json") }}
  "{{ $templateName }}": {{ $content | fromYaml | toJson | b64enc }}
  {{- else if ( or  (eq $ext ".yaml") (eq $ext ".yml")) }}
  "{{ $templateName }}": {{ $content | fromYaml | toYaml | b64enc }}
  {{- else }}
  {{- fail (printf "unknown file ext '%s' in template '%s'" $ext $templateName ) }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: d8-system-registry-manager-pki
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "d8-system-registry")) | nindent 2 }}
type: Opaque
data:
{{- range $.Values.systemRegistry.internal.pki.data }}
  {{ .key }}: {{ .value }}
{{- end }}

##### For specific env
{{- end }}
#####