##### For specific registryMode
{{- if $.Values.systemRegistry.registryMode }}
{{- if not (eq $.Values.systemRegistry.registryMode "Direct")  }}
#####

---
apiVersion: v1
kind: Service
metadata:
  name: system-registry-manager
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "system-registry-manager")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    targetPort: 8097
    port: 8097
  selector:
    app: system-registry-manager
---
apiVersion: v1
kind: Service
metadata:
  name: system-registry
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "system-registry")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-seaweed-metrics
    protocol: TCP
    targetPort: 9324
    port: 9324
  - name: http-distrib-metrics
    protocol: TCP
    targetPort: 5002
    port: 5002
  selector:
    component: system-registry

##### For specific registryMode
{{- end }}
{{- end }}
#####
