apiVersion: v1
kind: Service
metadata:
  name: system-registry-manager
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "system-registry-manager")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-healthz
    protocol: TCP
    targetPort: http-healthz
    port: 8097
  - name: metrics
    protocol: TCP
    targetPort: metrics
    port: 8081
  selector:
    app: system-registry-manager

---
apiVersion: v1
kind: Service
metadata:
  name: system-registry-staticpod-manager
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "system-registry-staticpod-manager")) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https-api
    protocol: TCP
    targetPort: https-api
    port: 4577
  - name: http-healthz
    protocol: TCP
    targetPort: http-healthz
    port: 8097
  selector:
    app: system-registry-staticpod-manager

---
apiVersion: v1
kind: Service
metadata:
  name: embedded-registry
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "embedded-registry")) | nindent 2 }}
spec:
  clusterIP: None
  selector:
    component: system-registry
  ports:
    - name: embedded-registry
      port: 5001
      protocol: TCP
      targetPort: emb-reg-dist
