##### For specific env
{{- if (eq $.Values.systemRegistry.environment "Vadim")  }}
#####

---
apiVersion: v1
kind: Service
metadata:
  name: system-registry-manager
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list . (dict "app" "system-registry-manager")) | nindent 2 }}
spec:
  clusterIP: None
  ports:
  - name: https
    protocol: TCP
    targetPort: 8097
    port: 8097
  selector:
    app: system-registry-manager

##### For specific env
{{- end }}
#####
