---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: distribution
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "distribution")) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 2 0) }} ## TODO temporary for matrix tests
  selector:
    matchLabels:
      app: distribution
